# Site settings
title: Heily's Blog
email: edelbteen@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta 
  (for Google search results) and in your feed.xml site description.

baseurl: "" # e.g., /blog (leave empty if using root)
url: "https://heily-tech.github.io"

# Social media
github_username: heily-tech
# twitter_username: jekyllrb

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag

# Collections
collections:
  categories:
    output: true
    permalink: /:collection/:path/

# Default settings for collections
defaults:
  - scope:
      path: ""
      type: categories
    values:
      layout: category

# Excluded files and directories (uncomment if needed)
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
